@startuml
skinparam linetype ortho
skinparam DefaultFontName Arial
skinparam shadowing false

skinparam Activity {
    BackgroundColor #FFFFCC
    BorderColor #B22222
    StartColor #B22222
    EndColor #B22222
    ArrowColor #B22222
}
skinparam ArrowColor #B22222

mainframe act Admin Menambah Data Kelas

|Admin|
start
:Pilih Menu "Data Kelas";
:Klik Tombol "Tambah Kelas";
:Isi Nama Kelas & Jurusan;
:Klik "Simpan";
|Sistem|
:Validasi Input;
if (Valid?) then (Ya)
    :Simpan ke Database;
    :Tampilkan Pesan Berhasil;
else (Tidak)
    :Tampilkan Pesan Error;
endif
|Admin|
:Lihat Data Tersimpan;
stop
@enduml
